export const createUsersTable = `
CREATE TABLE IF NOT EXISTS users(
id SERIAL PRIMARY KEY,
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
phone_number VARCHAR(20) NOT NULL,
password VARCHAR(225) NOT NULL,
created_at TIMESTAMP CURRENT DEFAULT_TIMESTAMP
)
`;
